const T=[
["Pacífico","#244b4f","#79b4a7","≈","Ríos, bosques, selvas, minería y pueblos étnicos forman parte de un territorio donde la relación con la tierra y los recursos resulta indispensable para comprender las dinámicas del conflicto.","https://www.comisiondelaverdad.co/pacifico-capitulo-1","El Carmen de Atrato","Una puerta audiovisual para acercarte a un municipio chocoano y observar cómo la guerra transforma vidas, memorias y relaciones con el territorio.","https://www.comisiondelaverdad.co/sites/default/files/2023-02/rv_carmen_atrato_master_web%20%28720p%29.mp4"],
["Valle del Cauca y norte del Cauca","#405447","#c0c66f","✣","Territorios ancestrales afro e indígenas se cruzan con tierras productivas, economías ilegales, propiedad y dinámicas contrainsurgentes. La mirada territorial ayuda a reconocer relaciones que una explicación monocausal dejaría por fuera.","https://www.comisiondelaverdad.co/valle-capitulo-1"],
["Nariño y sur del Cauca","#4c4b49","#c78d69","▲","Volcanes, Macizo Colombiano y territorios ancestrales forman el escenario de procesos de despojo, disputas por la tierra, economías ilegales y violencias ejercidas por distintos actores.","https://www.comisiondelaverdad.co/narino-capitulo-1"],
["Amazonía","#274a3a","#86a85f","♣","La historia territorial no comienza con la llegada de los actores armados. Explotación de recursos, colonización y violencias contra pueblos originarios forman capas históricas necesarias para comprender la región.","https://www.comisiondelaverdad.co/amazonia-capitulo-0","Mitú","Una pieza para acercarse a la toma de Mitú y a sus impactos en un territorio con fuerte presencia indígena, escuchando la guerra desde el Vaupés.","https://www.comisiondelaverdad.co/sites/default/files/2023-02/rv_mitu_master_web%20%28720p%29.mp4"],
["Orinoquía","#52604a","#d0c46b","≋","Colonización, pueblos indígenas y relaciones históricas con la Colombia central permiten observar cómo se configuraron y transformaron dinámicas sociales, políticas y armadas.","https://www.comisiondelaverdad.co/orinoquia-capitulo-1"],
["Frontera nororiental","#334c55","#e1a15d","⌖","Petróleo, frontera con Venezuela, cordillera y Llanos se entrelazan en una región cuya condición fronteriza es clave para comprender dinámicas económicas, políticas, sociales y armadas.","https://www.comisiondelaverdad.co/frontera-capitulo-1","Fronteras","¿Qué cambia cuando una frontera deja de mirarse como periferia? Esta pieza invita a cuestionar estigmas y a escuchar cómo sus habitantes nombran el territorio.","https://www.comisiondelaverdad.co/sites/default/files/2023-02/rv_frontera_master_web%20%28720p%29.mp4"],
["Centro","#514941","#caa26b","⌂","En la región central se aglutinaron hechos decisivos de la historia de la guerra y de la paz desde el segundo tercio del siglo XX, con efectos prolongados sobre distintas generaciones campesinas.","https://www.comisiondelaverdad.co/centro-capitulo-1","Roncesvalles","Un municipio recuerda una toma guerrillera que marcó la vida local. La pieza permite observar cómo un hecho armado permanece en la memoria de una comunidad.","https://www.comisiondelaverdad.co/sites/default/files/2023-02/rv_roncesvalles_master_web%20%28720p%29.mp4"],
["Dinámicas urbanas","#38434c","#8aa8b3","▥","La guerra tampoco fue únicamente rural. Crecimiento de las ciudades, población universitaria, protesta y expresiones armadas urbanas muestran otras formas del conflicto y sus conexiones territoriales.","https://www.comisiondelaverdad.co/dinamicas-capitulo-1"],
["Magdalena Medio y Santander","#3c4c43","#9ab6a3","⌇","Altos niveles de violencia conviven con una historia significativa de organización campesina, obrera y estudiantil. Mirar ambas dimensiones evita reducir el territorio únicamente a la victimización.","https://www.comisiondelaverdad.co/magdalena-medio-capitulo-1"],
["Caribe","#3d5960","#e4b765","☼","Riqueza natural y cultural y desigualdades persistentes forman parte de un contexto regional conectado con disputas por tierra, poder político y dinámicas armadas.","https://www.comisiondelaverdad.co/caribe-capitulo-1","Caribe","Una pieza que parte de la geografía y abre preguntas sobre tierra, poder, violencia y responsabilidades en el Caribe colombiano.","https://www.comisiondelaverdad.co/sites/default/files/2023-02/rv_caribe_master_web%20%28720p%29.mp4"],
["Noroccidente","#34493f","#9db07d","❦","Su posición entre dos mares y su función como corredor ayudan a comprender por qué ha sido escenario de disputas violentas y un espacio relevante en procesos políticos y económicos del país.","https://www.comisiondelaverdad.co/noroccidente-capitulo-1"]
];
mount.innerHTML=T.map((t,i)=>`<section class="territory" style="--tone:${t[1]};--accent:${t[2]}"><div class="territory-copy reveal"><div class="num">${String(i+1).padStart(2,"0")}</div><small>EXPEDIENTE TERRITORIAL</small><h2>${t[0]}</h2><p>${t[4]}</p><a href="${t[5]}" target="_blank" rel="noopener">Entrar al relato original ↗</a></div><div class="art reveal"><div class="orb"></div><div class="symbol">${t[3]}</div>${t[6]?`<aside class="revelacion"><small>REVELACIONES · ABRE OTRA HUELLA</small><h3>${t[6]}</h3><p>${t[7]}</p><button data-title="${t[6]}" data-desc="${t[7]}" data-video="${t[8]}">Ver audiovisual ▶</button></aside>`:""}</div></section>`).join("");
const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("on");o.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>o.observe(x));
addEventListener("scroll",()=>{bar.style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+"%"},{passive:true});
const d=document.querySelector("#video"),p=document.querySelector("#vp");document.addEventListener("click",e=>{const b=e.target.closest("[data-video]");if(!b)return;vt.textContent=b.dataset.title;vd.textContent=b.dataset.desc;p.src=b.dataset.video;vl.href=b.dataset.video;d.showModal()});close.onclick=()=>{p.pause();p.removeAttribute("src");p.load();d.close()};